name: synth-convo
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.11.9
  - pandas
  - numpy
  - pip
  - pip:
    - OpenAI
    - toml

# To create environment:
# conda env create -f environment.yml

# To activate:
# conda activate synth-convo

# To update the environment with changes from environment.yml:
# conda env update --file environment.yml --name synth-convo

# To stop:
# conda deactivate

# Delete the environment 
# conda remove --name synth-convo --all